export const FIREBASE_API_KEY = 'YOUR API KEY';
export const FIREBASE_AUTH_DOMAIN = 'YOUR AUTH DOMAIN';
export const FIREBASE_DATABASE_URL = 'YOUR DATABASE URL';
export const FIREBASE_PROJECT_ID = 'YOUR PROJECT ID';
export const FIREBASE_STORAGE_BUCKET = 'YOUR STORAGE BUCKET';
export const FIREBASE_MESSAGING_SENDER_ID = 'YOUR MESSAGING SENDER ID';